development:
  adapter: mysql2
  database: blog_development
  username: root
  password:
  host: localhost

test:
  adapter: mysql2
  database: blog_test
  username: root
  password:
  host: localhost

production:
  adapter: mysql2
  database: blog
  username: root
  password:
  host: localhost
